### ISSUE TITLE
Malfunction in webview

### ISSUE THREAD

**Issue by fuadmmnf** [AgoraIO/Basic-Video-Broadcasting#102]
I am using flutter_webview_plugin for showing the react project. When I join a channel  as audience no video stream is available. Rather sound is heart only. But if the host disconnects and reconnects the channel then the video is restored. Can I get some help regarding this issue?

**Comment by plutoless** [comment]
what do you mean by sound is heart only?

**Comment by fuadmmnf** [comment]
only audio was available..but it was a webview issue..
