### ISSUE TITLE
Saving the video locally

### ISSUE THREAD

**Issue by enriquejuan2** [AgoraIO/Basic-Video-Broadcasting#103]
I have successfully implemented the library into my app but i was wondering if it is possible to save the video to the local storage of the device or upload it to a cloud storage platform. 

Thanks in advance

**Comment by yoreland** [comment]
Hi, you may be interested with Agora's MediaPlayerKit:
https://docs.agora.io/en/Interactive%20Broadcast/mediaplayer_android?platform=Android

**Comment by yoreland** [comment]
Hi, if you just want to get the real time video recorded. The solution for you is the cloud recording.
Please check below guideline if it fit your requirement:
https://docs.agora.io/en/cloud-recording/product_cloud_recording

**Comment by enriquejuan2** [comment]
Thanks this is exactly what i am looking for.
