### ISSUE TITLE
Token IDs to replace App IDs

### ISSUE THREAD

**Issue by ChiGlobal** [AgoraIO/Basic-Video-Broadcasting#113]
Hi, I got a message that we're not supposed to use app IDs anymore but instead token IDs... Is this true?

**Comment by yoreland** [comment]
Hi, app id is not secure for production environment. But you could continue to use it for dev and testing purpose. :)

**Comment by ChiGlobal** [comment]
@yoreland oh ok great, thanks a lot... Cos I got a little confused 😅🙏🏼
