### ISSUE TITLE
Buttons not functioning

### ISSUE THREAD

**Issue by ChiGlobal** [AgoraIO/Basic-Video-Broadcasting#114]
Hi, what do I do... The buttons are not working
![Screenshot_20200817-180834.png](https://user-images.githubusercontent.com/68472603/90917440-cb375c00-e3da-11ea-88c1-018fee51cf12.png)

**Comment by yoreland** [comment]
which demo it is ? Is it openLive?

**Comment by ChiGlobal** [comment]
@yoreland hi, no it's not that one... This is made with flutter but I've resolved it already.. thanks 🙏🏼
