### ISSUE TITLE
Error: can not see video on broadcaster mode

### ISSUE THREAD

**Issue by Goriwideum** [AgoraIO/Basic-Video-Broadcasting#12]
Hi all support, 

we have downloaded the open live for Android, we pass the app to mobile device and enter in a channel but when select broadcaster mode the stream suscribed in web sample show black always.

Can you help us?

Thanks in advance.
![2019-03-25_11h27_00](https://user-images.githubusercontent.com/48910371/54912452-f4f00900-4ef0-11e9-9d26-d86535cd2ed5.png)

**Comment by plutoless** [comment]
@Goriwideum  can it play successfully if you press the "play" button on the video view? If yes, it could be related to [autoplay](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) issue

**Comment by Goriwideum** [comment]
> @Goriwideum can it play successfully if you press the "play" button on the video view? If yes, it could be related to [autoplay](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) issue

Hi plutoless!!!

No, not working even if you press "play" button, always video stay in looping mode and not do anything.

In web sample we have this code: stream.play('agora_remote' + stream.getId());    but not works.

Thanks.

**Comment by plutoless** [comment]
which codec are you using when you initialize your sdk client for web?
if you are using vp8, you may need to call enableWebSdkInteroperability from

**Comment by Goriwideum** [comment]
> which codec are you using when you initialize your sdk client for web?
> if you are using vp8, you may need to call enableWebSdkInteroperability from android

I don't know which code we are using in web sdk cause we not set it, I think that this code is setted by default inside .js SDK.

By other way, I have put this line (.enableWebSdkInteroperability(true);) after .enableVideo() and now works fine, we can see video from broadcaster mode in Open Live app sample.

Thanks a lot plutoless.

Best regards.
