### ISSUE TITLE
Please solve this

### ISSUE THREAD

**Issue by ishaang10** [AgoraIO/Basic-Video-Broadcasting#13]
https://stackoverflow.com/questions/55582887/i-want-to-integrate-my-app-with-broadcasting-it-but-landing-into-a-crash

**Comment by plutoless** [comment]
saw discussions going on in stackflow already.

**Comment by ishaang10** [comment]
Hey @plutoless can you share the link to the duscussion of the same..!! i haven't posted anything on stack yet

**Comment by plutoless** [comment]
it's right in the link you provided.
anyway it seems the crash is relevant to ugq which is not relevant to our SDK. Are you using our original demo?

**Comment by ishaang10** [comment]
oh sorry. i thought this is different thread. this issue has been solved. thanks
