### ISSUE TITLE
How to identify that host already start broadcast channel ?

### ISSUE THREAD

**Issue by hardiktgreydesk** [AgoraIO/Basic-Video-Broadcasting#137]
Hello team,

We have a requirement that user can join the broadcast channel which is hosted by a Tutor, But i want to know that when user try to join that channel and if that channel not yet broadcast by tutor. i want to give some error to user. How can we achieve that ?

**Comment by yoreland** [comment]
You'd better rely to your backend service to do this kind of requirement.
Another choice if you want to get real time notification when broadcast status updated, you could integrate Agora RTM SDK to do server-to-client push notification
