### ISSUE TITLE
Android & iOS to Website Live Streaming not working. Only audio is coming, video is not coming.

### ISSUE THREAD

**Issue by shubhra-ahead** [AgoraIO/Basic-Video-Broadcasting#142]
We have implemented this sdk at our end and facing the issue that when the user goes live from iOS or Android device to Website, then the live video is not displaying. 

Only the voice behind the video is audible,

Please provide assistance on this issue.

**Comment by yoreland** [comment]
One possible reason is wrongly used audio SDK. Can you double check?

**Comment by shubhra-ahead** [comment]
> One possible reason is wrongly used audio SDK. Can you double check?

As mentioned, we can hear the audio, but the issue is we can not see the video.

**Comment by 13268948473** [comment]
1.

**Comment by shubhra-ahead** [comment]
This issue is still open from 2021 and the we can replicate the same at our end multiple times.

Can we please get an update from Agora team on this?
