### ISSUE TITLE
运行 demo 一直报错。

### ISSUE THREAD

**Issue by felixcc** [AgoraIO/Basic-Video-Broadcasting#24]
![image](https://user-images.githubusercontent.com/459409/62532176-6a43f100-b876-11e9-9fb2-ba1ebd057328.png)

**Comment by brianxcli** [comment]
native libs 路径是如何设置的

**Comment by guohai** [comment]
如果是手动拷贝 jar/so 的话，看下 jniLibs 里面是否有对应的 so

**Comment by TongJiangyong** [comment]
应该是手动移动so包出错导致的问题，可以按一下的步骤check一下：
1、烦check一下so包有没有按正确的版本(arm64,armv7a,x86)移动到readme指定的位置
2、如果自己有配置gradle指定so包的加载路径，请确定下so包是否移动到指定的路径
