### ISSUE TITLE
How can i implement Basic - video Broadcasting in Angular 7 ?

### ISSUE THREAD

**Issue by thakorji007** [AgoraIO/Basic-Video-Broadcasting#38]
Hello sir or mem 
 can you please tell me how can i implement Basic - Video-Broadcasting in Angular 7 for Web ?

can you please Help me ?

**Comment by plutoless** [comment]
which part of using our sdk do you have problems?

**Comment by thakorji007** [comment]
Yes sir , 
using Agora web API i can create Channel on web , and also i can attached camera and microphone and it will show me on my browser , it can not connect by android or IOS side , and if android or IOS are creating Channel then in web can not connect it , and it is not showing in display area 

can you please help me to solve this particular issue ?

**Comment by plutoless** [comment]
for android/iOS, are you using native SDK?

**Comment by thakorji007** [comment]
Hello sir 
    i have solved most of issue , but i can't find a solution for one issue.

    ----------
    ISSUE 
   -----------    
       :   when i use when i run project as localhost then Agora API can access Media access like camera and microphone but when i run globally it , then it give me error Media can not access like camera or microphone 

can you please tell me why it is happens ?

**Comment by plutoless** [comment]
guess you are deploying to http? webrtc requires https
