### ISSUE TITLE
Error: Cannot find module '@csstools/normalize.css'

### ISSUE THREAD

**Issue by thesct22** [AgoraIO/Basic-Video-Broadcasting#39]
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Error: Cannot find module '@csstools/normalize.css'

**Comment by plutoless** [comment]
@thesct22 it seems your npm install is somehow not successful. please try deleting the node_moduels folder and npm install again
