### ISSUE TITLE
直播的时候进行定时截屏

### ISSUE THREAD

**Issue by ByHSH** [AgoraIO/Basic-Video-Broadcasting#4]
我是Android客户端开发,我想在直播的时候进行定时截屏，但是截屏的图片是上下颠倒的，请问有什么API可以使用，或者在截屏的用什么回调可以进行处理

**Comment by guohai** [comment]
@ByHSH 请问你用的什么截图的？

**Comment by guohai** [comment]
> MediaDataObserverPlugin.saveCaptureVideoSnapshot(filePath);

这是一个 bug，这个方法里面没有把 orientation 考虑进去。我们会想法修复下。

**Comment by guohai** [comment]
已经修复了 @ByHSH 

https://github.com/AgoraIO/Advanced-Video/commit/2aa1e2be2f1e9f468e310953e4ec385b4c3e7e9b
