### ISSUE TITLE
Giving No 'Access-Control-Allow-Origin' during calling Live Chanel  

### ISSUE THREAD

**Issue by thakorji007** [AgoraIO/Basic-Video-Broadcasting#40]
*when i calling Agora API for getting live chanel name from PostMan tool then it is successfully call but problem is that when I am trying to call Agora API using Angular7 , then i can't able to call Agora API and it giving me cross-origin whith 404 error. i have mantion exception below.*

    OPTIONS https://api.agora.io/dev/v1/channel/{App Id}/ 404 (Not Found)

    Access to XMLHttpRequest at 'https://api.agora.io/dev/v1/channel/{App Id}/' from origin MY IP has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by plutoless** [comment]
you need to replace {App Id} with your own one. also usually this api is not suitable to call from client directly, as it can be abused and your credential could also leak to client users. usually this api is used from your server side so that it does not require cors support

**Comment by plutoless** [comment]
closing here as it's not relevant to any samples in this repository. 
please talk to community for general enquiries about agora product.
https://docs.agora.io/en/Agora%20Platform/community?_ga=2.65742894.1887031822.1573724841-2140392182.1568170006
