### ISSUE TITLE
Can multiple users host a broadcast at the same time?

### ISSUE THREAD

**Issue by AxesandGrinds** [AgoraIO/Basic-Video-Broadcasting#47]
I understand that working with the demo, a user can either enter as a broadcaster or as the audience. My question is, can multiple users enter as broadcasters in the same channel while the remaining users enter as audience?

Thanks for your help.

**Comment by plutoless** [comment]
yes you can.

**Comment by AxesandGrinds** [comment]
For other users with the same question, I solved this issue by combining the Basic-Video-Broadcasting code with the interactive broadcasting code (https://github.com/AgoraIO/Advanced-Interactive-Broadcasting) such that if a user joins as a streamer with a particular uid (starts or ends with a particular keyword) then that user enters the broadcast in the smallAdapter. To remove the user from small video then simply have user leave channel, change user's uid back to original then enter the same channel again. But that would be taken care of with your signaling code.
