### ISSUE TITLE
Is Push Stream Necessary?

### ISSUE THREAD

**Issue by AxesandGrinds** [AgoraIO/Basic-Video-Broadcasting#48]
In the activity_live_room layout file there is an image view with the id: live_btn_push_stream
and the onclick function: onPushStreamClicked. I am new to broadcasting so I don't understand what the push stream is for. Is it necessary in order to create a broadcast? What is the purpose of the push stream? Can someone broadcast and have streamers watch the broadcast without a push stream?

Secondly, what is the maximum number of users who can watch a broadcast at the same time?

Thanks.

**Comment by plutoless** [comment]
@AxesandGrinds if you take a look at detail implementation you will notice the implementation is empty. that means it's not being used at all. to publish a stream you just need to make yourself a broadcaster and join the same channel.
there's no limitation for audience number

**Comment by AxesandGrinds** [comment]
Thank you for the explanation!
