### ISSUE TITLE
视频黑屏无法显示

### ISSUE THREAD

**Issue by rainver** [AgoraIO/Basic-Video-Broadcasting#53]
Nexus 5X / 8.1 / android studio 3.5.3
替换appid和token之后启动
使用生成token的字符串进入频道
选择主播模式
进入房间后黑屏
日志里有一些错误
请帮忙看看是什么问题
[agora-rtc.log](https://github.com/AgoraIO/Basic-Video-Broadcasting/files/4012312/agora-rtc.log)

**Comment by plutoless** [comment]
看起来是token匹配问题，你用token算的时候应该填了一个频道名，这个频道名是否和后来你加入频道时使用的频道名一致？

**Comment by rainver** [comment]
谢谢，搞明白了，原来这个demo项目没有用到access token，后台生成项目的时候选择只用appid验证，不要启用证书
