### ISSUE TITLE
推流端进入直播以后，本地视图黑屏是怎么回事啊 

### ISSUE THREAD

**Issue by lin1105** [AgoraIO/Basic-Video-Broadcasting#57]
token 和  频道名都是对应起来的

**Comment by lin1105** [comment]
拉流端能够正常看得到直播画面

**Comment by lin1105** [comment]
[agorasdk.log](https://github.com/AgoraIO/Basic-Video-Broadcasting/files/4280280/agorasdk.log)

**Comment by plutoless** [comment]
你跑的是openlive示例吗？用模拟器跑的还是真机跑的？换个设备是否正常？

**Comment by plutoless** [comment]
看日志频道加入应该成功了
