### ISSUE TITLE
Warning Code Help!!!!!

### ISSUE THREAD

**Issue by Zeeshan90** [AgoraIO/Basic-Video-Broadcasting#69]
Help!!!!!!
 i am getting this error in ios
warning code: invalid view
warning code: 16

**Comment by plutoless** [comment]
looks like the view you are setting is incorrect? which demo are you running?

**Comment by NayanBhut** [comment]
I am running iOS Demo. Current pod version in 3.0.0.2. I am also getting same warning.
warning code: invalid view
warning code: 16

As per demo when I join channel as audience I am getting this warning every time. When I join channel first time video appears and after if broadcaster mute their audio and unmute at that time I can only listen voice. No video is on screen.

Please help.

**Comment by CavanSu** [comment]
@NayanBhut 
Thank you for discovering this problem. When video stream is zero, I need reset video layout. you can see the latest commit, I fixed this problem.

warning code 16 causes by that view's width and height are 0 when it is related to AgoraRtcVideoCanvas, AgoraRtcEngineKit reports this warning code. After it is moved to AGEVideoContainer, it has normal size and renders video stream.

**Comment by NayanBhut** [comment]
@CavanSu Thank you for your quick response. I get the latest code and run on the device. I am seeing same issue. I am running swift code.

Steps for produce.

**Comment by plutoless** [comment]
@NayanBhut just merged @CavanSu 's commit into master. pls try again

**Comment by NayanBhut** [comment]
@plutoless I checked the latest commit. This commit solved my issue. Thanks for your quick response and solution.
